    const wordsList = [
        {word: 'SCHOOL', hint: 'Where you learn'},
        {word: 'FRIEND', hint: 'Someone you like to play with'},
        {word: 'PLANET', hint: 'Earth is one of these'},
        {word: 'ANIMAL', hint: 'Living creatures like dogs and cats'},
        {word: 'GARDEN', hint: 'Where plants and flowers grow'},
        {word: 'PENCIL', hint: 'Writing tool with lead inside'},
        {word: 'BANANA', hint: 'Yellow curved fruit'},
        {word: 'WINDOW', hint: 'Glass opening in a wall'},
        {word: 'JACKET', hint: 'Clothing worn to stay warm'},
        {word: 'PUZZLE', hint: 'Game with pieces to fit together'},
        {word: 'ORANGE', hint: 'Citrus fruit that shares name with a color'},
        {word: 'GUITAR', hint: 'Musical instrument with strings'},
        {word: 'PILLOW', hint: 'Soft cushion for your head'},
        {word: 'ROCKET', hint: 'Vehicle that travels to space'},
        {word: 'CASTLE', hint: 'Large building where kings and queens live'},
        {word: 'BRIDGE', hint: 'Structure built over rivers or roads'},
        {word: 'COOKIE', hint: 'Sweet baked treat'},
        {word: 'TURTLE', hint: 'Reptile with a shell'},
        {word: 'DOCTOR', hint: 'Person who helps sick people'},
        {word: 'WINTER', hint: 'Cold season with snow'},
        {word: 'SUMMER', hint: 'Warm season for swimming'},
        {word: 'CAMERA', hint: 'Device used to take pictures'},
        {word: 'POTATO', hint: 'Vegetable that grows underground'},
        {word: 'BASKET', hint: 'Container woven from flexible materials'},
        {word: 'RABBIT', hint: 'Animal with long ears that hops'},
        {word: 'CIRCUS', hint: 'Traveling show with performers and animals'},
        {word: 'MUSEUM', hint: 'Building where art and artifacts are displayed'},
        {word: 'BUTTER', hint: 'Dairy product spread on bread'},
        {word: 'ISLAND', hint: 'Land surrounded by water'},
        {word: 'JUNGLE', hint: 'Dense tropical forest'},
        {word: 'BOTTLE', hint: 'Container for liquids'},
        {word: 'DRAGON', hint: 'Mythical fire-breathing creature'},
        {word: 'MARKET', hint: 'Place where goods are bought and sold'},
        {word: 'HELMET', hint: 'Protective gear for your head'},
        {word: 'PENCIL', hint: 'Tool used for writing or drawing'},
        {word: 'FOREST', hint: 'Large area covered with trees'},
        {word: 'SOCCER', hint: 'Sport played with a round ball and feet'},
        {word: 'SPIDER', hint: 'Eight-legged creature that spins webs'},
        {word: 'CHEESE', hint: 'Dairy food often used on pizza'},
        {word: 'FLOWER', hint: 'Colorful part of a plant'},
        {word: 'WALLET', hint: 'Small case for carrying money'},
        {word: 'COFFEE', hint: 'Hot beverage made from beans'},
        {word: 'KITTEN', hint: 'Baby cat'},
        {word: 'PURPLE', hint: 'Color between red and blue'},
        {word: 'TENNIS', hint: 'Sport played with rackets and a ball'},
        {word: 'CARPET', hint: 'Floor covering made of fabric'},
        {word: 'MIRROR', hint: 'Surface that reflects your image'},
        {word: 'LEMON', hint: 'Sour yellow citrus fruit'},
        {word: 'SAILOR', hint: 'Person who works on a ship'},
        {word: 'PUPPET', hint: 'Toy figure moved by strings or hands'},
        {word: 'HOCKEY', hint: 'Sport played on ice with sticks'},
        {word: 'CANDLE', hint: 'Wax stick with wick that provides light'},
        {word: 'HAMMER', hint: 'Tool used to drive nails'},
        {word: 'TURKEY', hint: 'Large bird eaten at Thanksgiving'},
        {word: 'DESERT', hint: 'Hot, dry area with sand'},
        {word: 'LADDER', hint: 'Tool for climbing up and down'},
        {word: 'CARROT', hint: 'Orange vegetable that rabbits like'},
        {word: 'BUTTON', hint: 'Small disc used to fasten clothes'},
        {word: 'POLICE', hint: 'People who enforce laws'},
        {word: 'JACKET', hint: 'Outer garment with sleeves'},
        {word: 'DINNER', hint: 'Evening meal'},
        {word: 'TIGER', hint: 'Large striped wild cat'},
        {word: 'MUSIC', hint: 'Sounds organized to be pleasant'},
        {word: 'RIVER', hint: 'Large natural stream of water'},
        {word: 'PIZZA', hint: 'Italian dish with cheese and toppings'},
        {word: 'BEACH', hint: 'Sandy shore by the ocean'},
        {word: 'TRUCK', hint: 'Large vehicle for carrying goods'},
        {word: 'QUEEN', hint: 'Female ruler of a kingdom'},
        {word: 'APPLE', hint: 'Round fruit, often red or green'},
        {word: 'HOUSE', hint: 'Building where people live'},
        {word: 'CLOCK', hint: 'Device that shows the time'},
        {word: 'CHAIR', hint: 'Furniture for sitting'},
        {word: 'WATER', hint: 'Clear liquid essential for life'},
        {word: 'TRAIN', hint: 'Vehicle that runs on tracks'},
        {word: 'CLOUD', hint: 'White fluffy thing in the sky'},
        {word: 'BREAD', hint: 'Baked food made from flour'},
        {word: 'SNAKE', hint: 'Reptile with no legs'},
        {word: 'HORSE', hint: 'Animal people ride'},
        {word: 'OCEAN', hint: 'Large body of salt water'},
        {word: 'SHIRT', hint: 'Clothing worn on upper body'},
        {word: 'PHONE', hint: 'Device used to call people'},
        {word: 'TABLE', hint: 'Furniture with flat top and legs'},
        {word: 'SHARK', hint: 'Large fish with sharp teeth'},
        {word: 'MOUSE', hint: 'Small rodent or computer device'},
        {word: 'MOVIE', hint: 'Story shown on a screen'},
        {word: 'PAPER', hint: 'Material used for writing'},
        {word: 'MONEY', hint: 'Used to buy things'},
        {word: 'QUEEN', hint: 'Female monarch'},
        {word: 'NIGHT', hint: 'Time when it\'s dark outside'},
        {word: 'LIGHT', hint: 'Makes things visible'},
        {word: 'SPACE', hint: 'Area beyond Earth\'s atmosphere'},
        {word: 'GRASS', hint: 'Green plants in lawns'},
        {word: 'BABY', hint: 'Very young child'},
        {word: 'KITE', hint: 'Toy that flies in the wind'},
        {word: 'STAR', hint: 'Bright object in the night sky'},
        {word: 'CAKE', hint: 'Sweet dessert for celebrations'},
        {word: 'BIRD', hint: 'Animal with wings that can fly'},
        {word: 'BOOK', hint: 'Pages with words bound together'},
        {word: 'MILK', hint: 'White drink from cows'},
        {word: 'BALL', hint: 'Round object used in games'},
        {word: 'FISH', hint: 'Animal that lives in water'},
        {word: 'LION', hint: 'Large wild cat with a mane'},
        {word: 'SNOW', hint: 'White frozen precipitation'},
        {word: 'TREE', hint: 'Plant with trunk and branches'},
        {word: 'DOOR', hint: 'Entrance to a room or building'},
        {word: 'MOON', hint: 'Object that orbits Earth'},
        {word: 'KING', hint: 'Male ruler of a kingdom'},
        {word: 'FIRE', hint: 'Hot, burning phenomenon'},
        {word: 'RAIN', hint: 'Water falling from clouds'},
        {word: 'GOLD', hint: 'Precious yellow metal'},
        {word: 'FROG', hint: 'Green jumping amphibian'},
        {word: 'BOAT', hint: 'Vehicle that travels on water'},
        {word: 'DUCK', hint: 'Bird that swims in water'},
        {word: 'BEAR', hint: 'Large furry woodland animal'},
        {word: 'DESK', hint: 'Furniture used for writing'},
        {word: 'SOAP', hint: 'Used for washing'},
        {word: 'GIFT', hint: 'Something given to someone'},
        {word: 'CHEF', hint: 'Person who cooks professionally'},
        {word: 'GAME', hint: 'Activity played for fun'},
        {word: 'FARM', hint: 'Land used for growing crops'},
        {word: 'RING', hint: 'Circular piece of jewelry'},
        {word: 'WING', hint: 'Part of a bird used for flying'},
        {word: 'SONG', hint: 'Musical composition with words'},
        {word: 'ROAD', hint: 'Path for traveling'},
        {word: 'SHOE', hint: 'Footwear'},
        {word: 'BIKE', hint: 'Two-wheeled vehicle'},
        {word: 'NOSE', hint: 'Body part used for smelling'},
        {word: 'LAKE', hint: 'Large body of fresh water'},
        {word: 'COAT', hint: 'Warm outer clothing'},
        {word: 'GOAT', hint: 'Farm animal with horns'},
        {word: 'BELL', hint: 'Metal object that makes ringing sound'},
        {word: 'CORN', hint: 'Yellow vegetable with kernels'},
        {word: 'WIND', hint: 'Moving air outdoors'},
        {word: 'CRAB', hint: 'Sea creature with pincers'},
        {word: 'SHIP', hint: 'Large vessel for sea travel'},
        {word: 'FROG', hint: 'Amphibian that jumps and croaks'},
        {word: 'SOUP', hint: 'Liquid food eaten with a spoon'},
        {word: 'NEST', hint: 'Bird\'s home'},
        {word: 'ROCK', hint: 'Hard mineral material'},
        {word: 'WOOL', hint: 'Fiber from sheep'},
        {word: 'CAVE', hint: 'Natural underground space'},
        {word: 'CHEF', hint: 'Professional cook'},
        {word: 'ROPE', hint: 'Thick cord made by twisting fibers'},
        {word: 'DRUM', hint: 'Percussion musical instrument'},
        {word: 'SALT', hint: 'White crystal used to flavor food'},
        {word: 'WOLF', hint: 'Wild animal related to dogs'},
        {word: 'VEST', hint: 'Sleeveless garment'},
        {word: 'LAMP', hint: 'Device that gives light'},
        {word: 'PEAR', hint: 'Sweet fruit with narrow top'},
        {word: 'BOWL', hint: 'Round container for food'},
        {word: 'DEER', hint: 'Forest animal with antlers'},
        {word: 'SOAP', hint: 'Cleaning product that makes bubbles'},
        {word: 'BEAN', hint: 'Seed from a pod used as food'},
        {word: 'TAPE', hint: 'Sticky material in a roll'},
        {word: 'SEED', hint: 'Small part of plant that grows'},
        {word: 'LEAF', hint: 'Green flat part of a plant'},
        {word: 'BULB', hint: 'Part of a lamp or flower'},
        {word: 'STEM', hint: 'Main stalk of a plant'},
        {word: 'FOAM', hint: 'Light material full of bubbles'},
        {word: 'ROOF', hint: 'Top covering of a building'},
        {word: 'NAIL', hint: 'Metal spike or fingertip covering'},
        {word: 'SEAL', hint: 'Marine mammal or wax stamp'},
        {word: 'PIPE', hint: 'Tube for carrying water'},
        {word: 'WORM', hint: 'Long thin soft-bodied animal'},
        {word: 'CLAY', hint: 'Soft earth material used in pottery'},
        {word: 'TOAD', hint: 'Amphibian similar to a frog'},
        {word: 'KNOT', hint: 'Fastening made by tying rope'},
        {word: 'PLUM', hint: 'Purple fruit with smooth skin'},
        {word: 'YARN', hint: 'Spun thread used for knitting'},
        {word: 'MINT', hint: 'Herb with cool-tasting leaves'},
        {word: 'HIVE', hint: 'Home for bees'},
        {word: 'CUBE', hint: 'Box with six equal square sides'},
        {word: 'PUMP', hint: 'Device for moving fluids'},
        {word: 'FORK', hint: 'Eating utensil with prongs'},
        {word: 'MASK', hint: 'Covering for the face'},
        {word: 'MOTH', hint: 'Insect similar to a butterfly'},
        {word: 'PEEL', hint: 'Outer skin of fruits'},
        {word: 'ARCH', hint: 'Curved structure spanning an opening'},
        {word: 'DART', hint: 'Small pointed missile thrown by hand'},
        {word: 'DUST', hint: 'Fine dry particles of matter'},
        {word: 'HOOK', hint: 'Curved piece of metal for catching'},
        {word: 'IRIS', hint: 'Colored part of the eye or a flower'},
        {word: 'LIME', hint: 'Green citrus fruit'},
        {word: 'MOLD', hint: 'Fungus growth or shaping container'},
        {word: 'NEST', hint: 'Structure where birds lay eggs'},
        {word: 'OVEN', hint: 'Enclosed cooking appliance'},
        {word: 'PACT', hint: 'Formal agreement'},
        {word: 'QUILT', hint: 'Warm bed covering'},
        {word: 'RUST', hint: 'Reddish coating on iron'},
        {word: 'SAIL', hint: 'Canvas sheet on a boat'},
        {word: 'TANK', hint: 'Container for liquids or military vehicle'},
        {word: 'VASE', hint: 'Container for displaying flowers'},
        {word: 'WASP', hint: 'Stinging flying insect'},
        {word: 'YARN', hint: 'Thread used for knitting'},
        {word: 'ZOOM', hint: 'Move quickly or magnify'},
        {word: 'ACID', hint: 'Sour chemical substance'},
        {word: 'BARK', hint: 'Outer covering of a tree'},
        {word: 'CLAW', hint: 'Sharp nail on animal\'s foot'},
        {word: 'DOCK', hint: 'Platform at water\'s edge'},
        {word: 'ECHO', hint: 'Sound repeated by reflection'},
        {word: 'FOAM', hint: 'Mass of small bubbles'},
        {word: 'GERM', hint: 'Microscopic organism'},
        {word: 'HAIL', hint: 'Frozen rain'},
        {word: 'INCH', hint: 'Small unit of length'},
        {word: 'JOKE', hint: 'Something said to cause laughter'},
        {word: 'KNOB', hint: 'Round handle for opening doors'},
        {word: 'LACE', hint: 'Delicate fabric with pattern of holes'},
        {word: 'MIST', hint: 'Light fog or spray'},
        {word: 'NOON', hint: 'Middle of the day'},
        {word: 'OPAL', hint: 'Colorful gemstone'},
        {word: 'PALM', hint: 'Inner surface of hand or tropical tree'},
        {word: 'QUIZ', hint: 'Test of knowledge'},
        {word: 'RAFT', hint: 'Flat floating structure'},
        {word: 'SCAR', hint: 'Mark left by healed wound'},
        {word: 'TWIG', hint: 'Small branch of a tree'},
        {word: 'UNIT', hint: 'Single thing or group'},
        {word: 'VEIN', hint: 'Blood vessel or streak in rock'},
        {word: 'WEED', hint: 'Unwanted plant'},
        {word: 'YAWN', hint: 'Open mouth wide from tiredness'},
        {word: 'ZEST', hint: 'Outer colored part of citrus peel'},
        {word: 'ATOM', hint: 'Smallest unit of an element'},
        {word: 'BEAD', hint: 'Small decorative object with a hole'},
        {word: 'COIL', hint: 'Spiral of rope or wire'},
        {word: 'DENT', hint: 'Small hollow in a surface'},
        {word: 'EDGE', hint: 'Outside limit of an object'},
        {word: 'FLAP', hint: 'Something that hangs loose and moves'},
        {word: 'GLOW', hint: 'Emit steady light'},
        {word: 'HEAP', hint: 'Pile of things'},
        {word: 'IRON', hint: 'Metal element or pressing tool'},
        {word: 'JUNK', hint: 'Discarded items of little use'},
        {word: 'KEEL', hint: 'Bottom part of a ship\'s structure'},
        {word: 'LENS', hint: 'Curved piece of glass'},
        {word: 'MAZE', hint: 'Complex network of paths'},
        {word: 'NOOK', hint: 'Small corner or recess'},
        {word: 'OVAL', hint: 'Egg-shaped figure'},
        {word: 'POLE', hint: 'Long slender piece of wood or metal'},
        {word: 'QUAY', hint: 'Platform by water for loading ships'},
        {word: 'RAMP', hint: 'Sloping surface connecting different levels'},
        {word: 'SLED', hint: 'Vehicle that slides over snow'},
        {word: 'TRAY', hint: 'Flat receptacle for carrying things'},
        {word: 'URGE', hint: 'Strong desire or impulse'},
        {word: 'VINE', hint: 'Climbing or trailing plant'},
        {word: 'WAVE', hint: 'Moving ridge on water surface'},
        {word: 'YARN', hint: 'Continuous strand of twisted fibers'},
        {word: 'ZERO', hint: 'Number representing none'},
        {word: 'ARCH', hint: 'Curved structure'},
        {word: 'BEAM', hint: 'Ray of light or structural support'},
        {word: 'COAL', hint: 'Black fossil fuel'},
        {word: 'DICE', hint: 'Small cubes used in games'},
        {word: 'ETCH', hint: 'Cut into a surface'},
        {word: 'FERN', hint: 'Plant with feathery leaves'},
        {word: 'GLUE', hint: 'Sticky substance for bonding'},
        {word: 'HOOP', hint: 'Circular ring'},
        {word: 'ICON', hint: 'Symbol or representation'},
        {word: 'JADE', hint: 'Green gemstone'},
        {word: 'KELP', hint: 'Large seaweed'},
        {word: 'LAVA', hint: 'Molten rock from volcano'},
        {word: 'MANE', hint: 'Long hair on neck of horse or lion'},
        {word: 'NEST', hint: 'Bird\'s home'},
        {word: 'OATS', hint: 'Cereal grain'},
        {word: 'PEAK', hint: 'Pointed top of mountain'},
        {word: 'QUIP', hint: 'Clever remark'},
        {word: 'REED', hint: 'Tall grass-like plant'},
        {word: 'SASH', hint: 'Decorative band worn around waist'},
        {word: 'TUSK', hint: 'Long pointed tooth'},
        {word: 'UNDO', hint: 'Reverse an action'},
        {word: 'VASE', hint: 'Decorative container for flowers'},
        {word: 'WICK', hint: 'String in candle that burns'},
        {word: 'YARN', hint: 'Fiber for knitting'},
        {word: 'ZINC', hint: 'Metallic element'},
        {word: 'AURA', hint: 'Distinctive atmosphere or quality'},
        {word: 'BOLT', hint: 'Metal fastener or lightning strike'},
        {word: 'COVE', hint: 'Small sheltered bay'},
        {word: 'DUSK', hint: 'Time before nightfall'},
        {word: 'ELBOW', hint: 'Joint in the middle of arm'},
        {word: 'FLINT', hint: 'Hard stone used to make fire'},
        {word: 'GRILL', hint: 'Cooking device with metal bars'},
        {word: 'HATCH', hint: 'Opening or emerge from egg'},
        {word: 'IGLOO', hint: 'Dome-shaped snow house'},
        {word: 'JEWEL', hint: 'Precious stone'},
        {word: 'KAYAK', hint: 'Small narrow watercraft'},
        {word: 'LOTUS', hint: 'Water lily with floating leaves'},
        {word: 'MAPLE', hint: 'Tree with distinctive leaf'},
        {word: 'NICKEL', hint: 'Five-cent coin or metallic element'},
        {word: 'ONION', hint: 'Layered vegetable that makes eyes water'},
        {word: 'PRISM', hint: 'Transparent object that splits light'},
        {word: 'QUILT', hint: 'Multi-layered bedcover'},
        {word: 'RADAR', hint: 'System using radio waves to detect objects'},
        {word: 'SQUID', hint: 'Sea creature with ten arms'},
        {word: 'TULIP', hint: 'Spring flower with cup-shaped bloom'},
        {word: 'UTOPIA', hint: 'Imagined perfect place'},
        {word: 'VAPOR', hint: 'Gas form of a substance'},
        {word: 'WHALE', hint: 'Large marine mammal'},
        {word: 'YACHT', hint: 'Recreational sailing vessel'},
        {word: 'ZEBRA', hint: 'Black and white striped animal'},
        {word: 'AMBER', hint: 'Fossilized tree resin'},
        {word: 'BLOOM', hint: 'Flower or flourishing state'},
        {word: 'CORAL', hint: 'Marine organism forming reefs'},
        {word: 'DELTA', hint: 'Triangular area at river mouth'},
        {word: 'EMBER', hint: 'Glowing coal in dying fire'},
        {word: 'FLUTE', hint: 'Wind musical instrument'},
        {word: 'GRAVY', hint: 'Sauce made from meat juices'},
        {word: 'HEDGE', hint: 'Row of bushes forming boundary'},
        {word: 'IVORY', hint: 'Hard white material from tusks'},
        {word: 'JELLY', hint: 'Soft, semi-solid food'},
        {word: 'KOALA', hint: 'Australian marsupial that eats eucalyptus'},
        {word: 'LINEN', hint: 'Fabric made from flax'},
        {word: 'MOOSE', hint: 'Large deer with broad antlers'},
        {word: 'NINJA', hint: 'Japanese warrior skilled in stealth'},
        {word: 'OPERA', hint: 'Musical drama with singing'},
        {word: 'PANDA', hint: 'Black and white bear from China'},
        {word: 'QUILL', hint: 'Feather used as writing pen'},
        {word: 'RAVEN', hint: 'Large black bird'},
        {word: 'STRAW', hint: 'Dried stalks of grain or drinking tube'},
        {word: 'THORN', hint: 'Sharp pointed growth on plant'},
        {word: 'UMPIRE', hint: 'Person who enforces rules in sports'},
        {word: 'VOWEL', hint: 'A, E, I, O, U in alphabet'},
        {word: 'WALNUT', hint: 'Wrinkled edible nut'},
        {word: 'XYLOPHONE', hint: 'Musical instrument with wooden bars'},
        {word: 'YOGURT', hint: 'Fermented dairy product'},
        {word: 'ANCHOR', hint: 'Device that holds ship in place'},
        {word: 'BREEZE', hint: 'Gentle wind'},
        {word: 'CANVAS', hint: 'Strong cloth for painting or sails'},
        {word: 'DIAMOND', hint: 'Precious gemstone'},
        {word: 'ECLIPSE', hint: 'Blocking of light from one celestial body'},
        {word: 'FOSSIL', hint: 'Preserved remains of ancient organism'},
        {word: 'GLACIER', hint: 'Slow-moving mass of ice'},
        {word: 'HORIZON', hint: 'Line where earth meets sky'},
        {word: 'INSECT', hint: 'Small invertebrate animal with six legs'},
        {word: 'JASMINE', hint: 'Fragrant flowering plant'},
        {word: 'KANGAROO', hint: 'Australian animal that hops'},
        {word: 'LANTERN', hint: 'Portable light with protective case'},
        {word: 'MAGNET', hint: 'Object that attracts iron'},
        {word: 'NECKLACE', hint: 'Jewelry worn around neck'},
        {word: 'OCTOPUS', hint: 'Sea creature with eight arms'},
        {word: 'PEACOCK', hint: 'Male bird with colorful tail feathers'},
        {word: 'QUARTER', hint: 'Twenty-five cents or one-fourth'},
        {word: 'RAINBOW', hint: 'Arc of colors in the sky'},
        {word: 'SCISSORS', hint: 'Cutting tool with two blades'},
        {word: 'TORNADO', hint: 'Violent rotating column of air'},
        {word: 'UMBRELLA', hint: 'Device that protects from rain'},
        {word: 'VOLCANO', hint: 'Mountain that erupts lava'},
        {word: 'WHISTLE', hint: 'Device that makes high-pitched sound'},
        {word: 'XYLOPHONE', hint: 'Percussion instrument with wooden bars'},
        {word: 'YESTERDAY', hint: 'Day before today'},
        {word: 'ZUCCHINI', hint: 'Green summer squash'},
        {word: 'AIRPLANE', hint: 'Flying vehicle with wings'},
        {word: 'BUTTERFLY', hint: 'Insect with colorful wings'},
        {word: 'CALENDAR', hint: 'System for organizing days and months'},
        {word: 'DINOSAUR', hint: 'Extinct reptile from millions of years ago'},
        {word: 'ELEPHANT', hint: 'Large animal with trunk and tusks'},
        {word: 'FLAMINGO', hint: 'Pink wading bird that stands on one leg'},
        {word: 'GIRAFFE', hint: 'Tall animal with long neck'},
        {word: 'HOSPITAL', hint: 'Building where sick people are treated'},
        {word: 'IGUANA', hint: 'Large lizard with spines'},
        {word: 'JELLYFISH', hint: 'Sea creature with tentacles'},
        {word: 'KANGAROO', hint: 'Animal that carries babies in pouch'},
        {word: 'LIBRARY', hint: 'Place with many books to borrow'},
        {word: 'MOUNTAIN', hint: 'Very high landform with peak'},
        {word: 'NOODLES', hint: 'Long thin strips of pasta'},
        {word: 'OCTAGON', hint: 'Shape with eight sides'},
        {word: 'PENGUIN', hint: 'Black and white bird that cannot fly'},
        {word: 'QUESTION', hint: 'Sentence asking for information'},
        {word: 'RAINBOW', hint: 'Colorful arc in sky after rain'},
        {word: 'SANDWICH', hint: 'Food with filling between bread slices'},
        {word: 'TELESCOPE', hint: 'Instrument for viewing distant objects'},
        {word: 'UNICORN', hint: 'Mythical horse with single horn'},
        {word: 'VACATION', hint: 'Period of time for rest and travel'},
        {word: 'WATERFALL', hint: 'Water flowing over edge of cliff'},
        {word: 'XYLOPHONE', hint: 'Musical instrument with wooden bars'},
        {word: 'YOGURT', hint: 'Creamy fermented milk food'},
        {word: 'ZIPPER', hint: 'Device with interlocking teeth for fastening'},
        {word: 'ALLIGATOR', hint: 'Large reptile similar to crocodile'},
        {word: 'BLUEBERRY', hint: 'Small round blue fruit'},
        {word: 'CHOCOLATE', hint: 'Sweet food made from cocoa'},
        {word: 'DRAGONFLY', hint: 'Insect with transparent wings'},
        {word: 'EVERGREEN', hint: 'Tree that keeps leaves all year'},
        {word: 'FIREPLACE', hint: 'Structure where indoor fire is made'},
        {word: 'GRASSHOPPER', hint: 'Jumping insect that makes chirping sounds'},
        {word: 'HAMBURGER', hint: 'Sandwich with ground meat patty'},
        {word: 'INSTRUMENT', hint: 'Tool for making music'},
        {word: 'JELLYBEAN', hint: 'Small bean-shaped candy'},
        {word: 'KEYBOARD', hint: 'Set of keys for typing or playing music'},
        {word: 'LIGHTHOUSE', hint: 'Tower with light to guide ships'},
        {word: 'MICROPHONE', hint: 'Device that amplifies your voice'},
        {word: 'NEWSPAPER', hint: 'Printed publication with news'},
        {word: 'ORCHESTRA', hint: 'Large group of musicians'},
        {word: 'PINEAPPLE', hint: 'Tropical fruit with spiky top'},
           {word: 'QUICKSAND', hint: 'Dangerous loose wet sand that sucks things down'},
        {word: 'RECTANGLE', hint: 'Shape with four sides and four right angles'},
        {word: 'STRAWBERRY', hint: 'Red fruit with seeds on outside'},
        {word: 'TELESCOPE', hint: 'Instrument for viewing distant objects'},
        {word: 'UMBRELLA', hint: 'Device that protects from rain or sun'},
        {word: 'VEGETABLE', hint: 'Plant part eaten as food'},
        {word: 'WATERMELON', hint: 'Large fruit with green rind and red flesh'},
        {word: 'XYLOPHONE', hint: 'Musical instrument with wooden bars struck by mallets'},
        {word: 'YESTERDAY', hint: 'The day before today'},
        {word: 'ZOOKEEPER', hint: 'Person who cares for animals in a zoo'},
        {word: 'ADVENTURE', hint: 'Exciting or unusual experience'},
        {word: 'BUTTERFLY', hint: 'Insect with colorful wings'},
        {word: 'CROCODILE', hint: 'Large reptile with powerful jaws'},
        {word: 'DETECTIVE', hint: 'Person who investigates crimes'},
        {word: 'ELEPHANT', hint: 'Largest land mammal with trunk'},
        {word: 'FURNITURE', hint: 'Movable objects in a room'},
        {word: 'GRASSLAND', hint: 'Large area covered with grass'},
        {word: 'HAPPINESS', hint: 'Feeling of joy or contentment'},
        {word: 'INVISIBLE', hint: 'Cannot be seen'},
        {word: 'JELLYFISH', hint: 'Sea creature with tentacles'},
        {word: 'KANGAROO', hint: 'Australian animal that hops'},
        {word: 'LEMONADE', hint: 'Drink made from lemons and sugar'},
        {word: 'MUSHROOM', hint: 'Fungus with cap and stem'},
        {word: 'NIGHTTIME', hint: 'Period of darkness when sun is down'},
        {word: 'OCTOPUS', hint: 'Sea animal with eight arms'},
        {word: 'PARACHUTE', hint: 'Device for slowing fall through air'},
        {word: 'QUESTION', hint: 'Sentence that asks for information'},
        {word: 'RAINCOAT', hint: 'Waterproof jacket for wet weather'},
        {word: 'SANDWICH', hint: 'Food with filling between bread'},
        {word: 'TRIANGLE', hint: 'Shape with three sides'},
        {word: 'UNIVERSE', hint: 'All of space and everything in it'},
        {word: 'VACATION', hint: 'Period of time for travel or rest'},
        {word: 'WHISKERS', hint: 'Hair growing on animal\'s face'},
        {word: 'XYLOPHONE', hint: 'Musical instrument with wooden bars'},
        {word: 'YOGHURT', hint: 'Fermented milk product'},
        {word: 'ZUCCHINI', hint: 'Green summer squash vegetable'},
        {word: 'ASTRONAUT', hint: 'Person who travels in space'},
        {word: 'BACKPACK', hint: 'Bag carried on your back'},
        {word: 'CAMPFIRE', hint: 'Outdoor fire for cooking or warmth'},
        {word: 'DINOSAUR', hint: 'Extinct prehistoric reptile'},
        {word: 'ELEVATOR', hint: 'Moving compartment between floors'},
        {word: 'FESTIVAL', hint: 'Celebration or special event'},
        {word: 'GRAPEFRUIT', hint: 'Large citrus fruit'},
        {word: 'HOSPITAL', hint: 'Building where sick people are treated'},
        {word: 'INTERNET', hint: 'Global computer network'},
        {word: 'JACKFRUIT', hint: 'Large tropical fruit'},
        {word: 'KILOMETER', hint: 'Unit of distance (1000 meters)'},
        {word: 'LULLABY', hint: 'Gentle song to help babies sleep'},
        {word: 'MOSQUITO', hint: 'Small flying insect that bites'},
        {word: 'NOTEBOOK', hint: 'Book with blank pages for writing'},
        {word: 'OBSTACLE', hint: 'Something that blocks your way'},
        {word: 'PANCAKES', hint: 'Flat cakes cooked in a pan'},
        {word: 'QUICKSAND', hint: 'Deep wet sand that traps things'},
        {word: 'RAINFOREST', hint: 'Dense forest with high rainfall'},
        {word: 'SUBMARINE', hint: 'Vessel that travels underwater'},
        {word: 'TELEPHONE', hint: 'Device used for talking to people far away'},
        {word: 'UNICYCLE', hint: 'One-wheeled vehicle'},
        {word: 'VOLCANO', hint: 'Mountain that can erupt'},
        {word: 'WINDMILL', hint: 'Building with sails turned by wind'},
        {word: 'XYLOPHONE', hint: 'Percussion instrument with wooden bars'},
        {word: 'YESTERDAY', hint: 'Day before today'},
        {word: 'ZOOLOGIST', hint: 'Scientist who studies animals'},
        {word: 'ACROBAT', hint: 'Person who performs gymnastic feats'},
        {word: 'BIRTHDAY', hint: 'Anniversary of the day you were born'},
        {word: 'CARNIVAL', hint: 'Traveling amusement show'},
        {word: 'DOLPHIN', hint: 'Intelligent marine mammal'},
        {word: 'EARRING', hint: 'Jewelry worn on ears'},
        {word: 'FOUNTAIN', hint: 'Ornamental water feature'},
        {word: 'GORILLA', hint: 'Large powerful ape'},
        {word: 'HAIRCUT', hint: 'Trimming or styling of hair'},
        {word: 'ICEBERG', hint: 'Large floating mass of ice'},
        {word: 'JEWELRY', hint: 'Decorative items worn on body'},
        {word: 'KEYBOARD', hint: 'Set of keys for typing or playing music'},
        {word: 'LANTERN', hint: 'Portable light with protective case'},
        {word: 'MEDICINE', hint: 'Substance used to treat illness'},
        {word: 'NECKLACE', hint: 'Ornament worn around neck'},
        {word: 'OBSTACLE', hint: 'Thing that blocks your way'},
        {word: 'POPCORN', hint: 'Snack made from heated corn kernels'},
        {word: 'QUARREL', hint: 'Angry argument or disagreement'},
        {word: 'RACCOON', hint: 'Mammal with black mask-like face marking'},
        {word: 'SAILBOAT', hint: 'Boat propelled by wind'},
        {word: 'TOOTHBRUSH', hint: 'Tool for cleaning teeth'},
        {word: 'UNIFORM', hint: 'Standard clothing worn by group members'},
        {word: 'VAMPIRE', hint: 'Mythical creature that drinks blood'},
        {word: 'WEEKEND', hint: 'Saturday and Sunday'},
        {word: 'YOGURT', hint: 'Fermented dairy product'},
        {word: 'ALPHABET', hint: 'Set of letters used in language'},
        {word: 'BALLOON', hint: 'Inflated rubber bag'},
        {word: 'CAMERA', hint: 'Device for taking photographs'},
        {word: 'DIAMOND', hint: 'Precious gemstone'},
        {word: 'ENVELOPE', hint: 'Paper container for letters'},
        {word: 'FEATHER', hint: 'Light growth covering birds'},
        {word: 'GARBAGE', hint: 'Waste material to be thrown away'},
        {word: 'HAMMOCK', hint: 'Swinging bed suspended between supports'},
        {word: 'INSECT', hint: 'Small invertebrate animal with six legs'},
        {word: 'JOURNEY', hint: 'Travel from one place to another'},
        {word: 'KITCHEN', hint: 'Room where food is prepared'},
        {word: 'LEATHER', hint: 'Material made from animal skin'},
        {word: 'MAGICIAN', hint: 'Person who performs magic tricks'},
        {word: 'NOODLES', hint: 'Long thin strips of pasta'},
        {word: 'OSTRICH', hint: 'Large flightless bird'},
        {word: 'PERFUME', hint: 'Fragrant liquid worn on body'},
        {word: 'QUARTER', hint: 'One fourth of something'},
        {word: 'RAINBOW', hint: 'Arc of colors in the sky after rain'},
        {word: 'SNOWMAN', hint: 'Figure made from snow'},
        {word: 'THUNDER', hint: 'Loud sound that follows lightning'},
        {word: 'UKULELE', hint: 'Small four-stringed guitar'},
        {word: 'VICTORY', hint: 'Success in contest or struggle'},
        {word: 'WHISTLE', hint: 'Device that makes high-pitched sound'},
        {word: 'YOGURT', hint: 'Fermented milk food'},
        {word: 'AIRPORT', hint: 'Place where airplanes take off and land'},
        {word: 'BICYCLE', hint: 'Two-wheeled vehicle'},
        {word: 'COMPASS', hint: 'Instrument showing directions'},
        {word: 'DOORBELL', hint: 'Button that rings to signal arrival'},
        {word: 'EARPHONES', hint: 'Small speakers worn on ears'},
        {word: 'FIREWORKS', hint: 'Explosive devices for display'},
        {word: 'GOLDFISH', hint: 'Small orange aquarium fish'},
        {word: 'HIGHWAY', hint: 'Main public road'},
        {word: 'ICECREAM', hint: 'Frozen dairy dessert'},
        {word: 'JUGGLER', hint: 'Person who tosses objects in the air'},
        {word: 'KETCHUP', hint: 'Tomato-based condiment'},
        {word: 'LOBSTER', hint: 'Large marine crustacean'},
        {word: 'MAILBOX', hint: 'Container for receiving mail'},
        {word: 'NAPKIN', hint: 'Small cloth for wiping mouth'},
        {word: 'OATMEAL', hint: 'Breakfast food made from oats'},
        {word: 'PAJAMAS', hint: 'Clothes worn for sleeping'},
        {word: 'QUICKSAND', hint: 'Wet sand that objects sink into'},
        {word: 'RAILWAY', hint: 'Track for trains'},
        {word: 'SEESAW', hint: 'Playground equipment that goes up and down'},
        {word: 'TEAPOT', hint: 'Container for brewing tea'},
        {word: 'UMBRELLA', hint: 'Device that protects from rain'},
        {word: 'VITAMIN', hint: 'Nutrient needed in small amounts'},
        {word: 'WEBSITE', hint: 'Collection of pages on internet'},
        {word: 'XYLOPHONE', hint: 'Percussion instrument with wooden bars'},
        {word: 'YARDSTICK', hint: 'Measuring tool three feet long'},
        {word: 'ZIPPER', hint: 'Fastener with interlocking teeth'},
        {word: 'APRICOT', hint: 'Small orange fruit'},
        {word: 'BLANKET', hint: 'Covering used on bed for warmth'},
        {word: 'CACTUS', hint: 'Desert plant with spines'},
        {word: 'DOMINO', hint: 'Small rectangular tile for games'},
        {word: 'ECLIPSE', hint: 'Blocking of light from one celestial body'},
        {word: 'FRISBEE', hint: 'Flying disc thrown for recreation'},
        {word: 'GLACIER', hint: 'Large mass of ice moving slowly'},
        {word: 'HAIRPIN', hint: 'Small pin for holding hair in place'},
        {word: 'ISLAND', hint: 'Land surrounded by water'},
        {word: 'JIGSAW', hint: 'Puzzle with interlocking pieces'},
        {word: 'KENNEL', hint: 'House for a dog'},
        {word: 'LOLLIPOP', hint: 'Sweet on a stick'},
        {word: 'MITTEN', hint: 'Hand covering with section for thumb only'},
        {word: 'NEEDLE', hint: 'Thin pointed tool for sewing'},
        {word: 'OYSTER', hint: 'Shellfish that can produce pearls'},
        {word: 'PUMPKIN', hint: 'Large orange squash'},
        {word: 'QUILT', hint: 'Thick bedcover with padding'},
        {word: 'RIBBON', hint: 'Narrow strip of fabric for decoration'},
        {word: 'STATUE', hint: 'Sculpture of person or animal'},
        {word: 'TRUMPET', hint: 'Brass musical instrument'},
        {word: 'UNICORN', hint: 'Mythical horse with single horn'},
        {word: 'VOLCANO', hint: 'Mountain that erupts'},
        {word: 'WALNUT', hint: 'Edible nut with wrinkled shell'},
        {word: 'YOGURT', hint: 'Fermented milk product'},
        {word: 'ZEBRA', hint: 'Black and white striped animal'},
        {word: 'AUTUMN', hint: 'Season between summer and winter'},
        {word: 'BUBBLE', hint: 'Sphere of liquid enclosing air'},
        {word: 'CRAYON', hint: 'Colored wax stick for drawing'},
        {word: 'DONKEY', hint: 'Animal related to horse with long ears'},
        {word: 'ERASER', hint: 'Object used to remove pencil marks'},
        {word: 'FARMER', hint: 'Person who works on a farm'},
        {word: 'GLOVES', hint: 'Hand coverings with separate fingers'},
        {word: 'HAMMER', hint: 'Tool for driving nails'},
        {word: 'IGLOO', hint: 'Dome-shaped snow house'},
        {word: 'JACKET', hint: 'Short coat'},
        {word: 'KETTLE', hint: 'Container for boiling water'},
        {word: 'LEMON', hint: 'Yellow citrus fruit'},
        {word: 'MAGNET', hint: 'Object that attracts iron'},
        {word: 'NICKEL', hint: 'Five-cent coin'},
        {word: 'ORANGE', hint: 'Round citrus fruit'},
        {word: 'PEPPER', hint: 'Spice that makes you sneeze'},
        {word: 'QUIVER', hint: 'Container for arrows'},
        {word: 'ROCKET', hint: 'Vehicle that travels into space'},
        {word: 'SADDLE', hint: 'Seat for rider on horse'},
        {word: 'TICKET', hint: 'Printed slip showing payment'},
        {word: 'UNCLE', hint: 'Brother of your parent'},
        {word: 'VIOLIN', hint: 'Stringed musical instrument'},
        {word: 'WINDOW', hint: 'Opening in wall with glass'},
        {word: 'YELLOW', hint: 'Color of bananas and lemons'},
        {word: 'ZOMBIE', hint: 'Walking dead person in stories'},
        {word: 'ACORN', hint: 'Seed of an oak tree'},
        {word: 'BRUSH', hint: 'Tool with bristles'},
        {word: 'CLOCK', hint: 'Device that shows time'},
        {word: 'DAISY', hint: 'White flower with yellow center'},
        {word: 'EAGLE', hint: 'Large bird of prey'},
        {word: 'FUDGE', hint: 'Soft sweet chocolate candy'},
        {word: 'GOOSE', hint: 'Large waterfowl with long neck'},
        {word: 'HONEY', hint: 'Sweet food made by bees'},
        {word: 'IGLOO', hint: 'Snow house'},
        {word: 'JEWEL', hint: 'Precious stone'},
        {word: 'KOALA', hint: 'Australian animal that eats eucalyptus'},
        {word: 'LEMON', hint: 'Sour yellow fruit'},
        {word: 'MELON', hint: 'Sweet juicy fruit with thick rind'},
        {word: 'NURSE', hint: 'Person who cares for sick people'},
        {word: 'OCEAN', hint: 'Vast body of saltwater'},
        {word: 'PEACH', hint: 'Soft juicy fruit with fuzzy skin'},
        {word: 'QUEEN', hint: 'Female ruler of a country'},
        {word: 'RULER', hint: 'Tool for measuring or drawing straight lines'},
        {word: 'SUGAR', hint: 'Sweet crystalline substance'},
        {word: 'TIGER', hint: 'Large wild cat with stripes'},
        {word: 'USHER', hint: 'Person who shows people to seats'},
        {word: 'VAULT', hint: 'Secure storage for valuables'},
        {word: 'WAGON', hint: 'Four-wheeled vehicle pulled by animal'},
        {word: 'XEROX', hint: 'Brand name for photocopier'},
        {word: 'YACHT', hint: 'Recreational sailing vessel'},
        {word: 'ZESTY', hint: 'Full of flavor or enthusiasm'},
        {word: 'ALARM', hint: 'Device that warns or alerts'},
        {word: 'BAGEL', hint: 'Ring-shaped bread roll'},
        {word: 'CAMEL', hint: 'Desert animal with humps'},
        {word: 'DENIM', hint: 'Sturdy cotton fabric for jeans'},
        {word: 'EAGLE', hint: 'Large bird with hooked beak'},
        {word: 'FENCE', hint: 'Structure enclosing an area'},
        {word: 'GRAPE', hint: 'Small round fruit growing in clusters'},
        {word: 'HOTEL', hint: 'Building offering rooms to travelers'},
        {word: 'IMAGE', hint: 'Picture or representation'},
        {word: 'JUICE', hint: 'Liquid from fruits or vegetables'},
        {word: 'KIOSK', hint: 'Small stand selling goods'},
        {word: 'LINEN', hint: 'Fabric made from flax'},
        {word: 'MOTEL', hint: 'Roadside hotel for motorists'},
        {word: 'NOVEL', hint: 'Long fictional story in book form'},
        {word: 'OLIVE', hint: 'Small oval fruit used for oil'},
        {word: 'PIANO', hint: 'Musical instrument with keys'},
        {word: 'QUAIL', hint: 'Small ground-dwelling bird'},
        {word: 'RADIO', hint: 'Device receiving broadcast signals'},
        {word: 'STOVE', hint: 'Appliance for cooking food'},
        {word: 'TOWEL', hint: 'Absorbent cloth for drying'},
        {word: 'URBAN', hint: 'Relating to a city'},
        {word: 'VAPOR', hint: 'Moisture suspended in air'},
        {word: 'WAFER', hint: 'Thin crisp cookie'},
        {word: 'XENON', hint: 'Chemical element used in lights'},
        {word: 'YACHT', hint: 'Luxury sailing vessel'},
        {word: 'ZEBRA', hint: 'African animal with black and white stripes'},
        {word: 'ANKLE', hint: 'Joint between foot and leg'},
        {word: 'BEACH', hint: 'Sandy shore by ocean'},
        {word: 'CANDY', hint: 'Sweet sugary treat'},
        {word: 'DANCE', hint: 'Move rhythmically to music'},
        {word: 'ELBOW', hint: 'Joint in middle of arm'},
        {word: 'FAIRY', hint: 'Magical tiny being with wings'},
        {word: 'GHOST', hint: 'Spirit of dead person'},
        {word: 'HEART', hint: 'Organ that pumps blood'},
        {word: 'IVORY', hint: 'Hard white material from tusks'},
        {word: 'JEANS', hint: 'Pants made from denim'},
        {word: 'KIWI', hint: 'Fuzzy brown fruit with green flesh'},
        {word: 'LEMON', hint: 'Sour yellow citrus fruit'},
        {word: 'MANGO', hint: 'Tropical fruit with orange flesh'},
        {word: 'NORTH', hint: 'Direction toward the North Pole'},
        {word: 'OPERA', hint: 'Musical drama with singing'},
        {word: 'PASTA', hint: 'Italian food made from dough'},
        {word: 'QUIET', hint: 'Making little or no noise'},
        {word: 'ROBIN', hint: 'Small bird with red breast'},
        {word: 'SCARF', hint: 'Fabric worn around neck'},
        {word: 'TULIP', hint: 'Spring flower with cup-shaped bloom'},
        {word: 'UNCLE', hint: 'Brother of your parent'},
        {word: 'VOICE', hint: 'Sound made when speaking'},
        {word: 'WATCH', hint: 'Device worn to tell time'},
        {word: 'XEROX', hint: 'Make a photocopy'},
        {word: 'YOUTH', hint: 'Period between childhood and adult age'},
        {word: 'ZEBRA', hint: 'Animal with black and white stripes'},
        {word: 'APPLE', hint: 'Round fruit, often red or green'},
        {word: 'BREAD', hint: 'Baked food made from flour'},
        {word: 'CHAIR', hint: 'Furniture for sitting'},
        {word: 'DREAM', hint: 'Images and thoughts during sleep'},
        {word: 'EARTH', hint: 'Planet we live on'},
        {word: 'FLUTE', hint: 'Wind musical instrument'},
        {word: 'GLOVE', hint: 'Covering for the hand'},
        {word: 'HORSE', hint: 'Large four-legged animal for riding'},
        {word: 'IMAGE', hint: 'Visual representation'},
        {word: 'JELLY', hint: 'Soft, semi-solid food'},
        {word: 'KNIFE', hint: 'Cutting tool with blade'},
        {word: 'LIGHT', hint: 'Brightness that lets us see'},
        {word: 'MUSIC', hint: 'Sounds organized to be pleasant'},
        {word: 'NIGHT', hint: 'Time of darkness when sun is down'},
        {word: 'OCEAN', hint: 'Vast body of salt water'},
        {word: 'PLANT', hint: 'Living organism that grows in soil'},
        {word: 'QUEEN', hint: 'Female ruler of a country'},
        {word: 'RIVER', hint: 'Large natural stream of water'},
        {word: 'SMILE', hint: 'Happy facial expression'},
        {word: 'TIGER', hint: 'Large wild cat with stripes'},
        {word: 'UNDER', hint: 'Below or beneath something'},
        {word: 'VOICE', hint: 'Sound made when speaking'},
        {word: 'WATER', hint: 'Clear liquid essential for life'},
        {word: 'XEROX', hint: 'Make a copy of a document'},
        {word: 'YOUNG', hint: 'In early stage of life'},
        {word: 'ZESTY', hint: 'Having a strong, pleasant flavor'}
    ];
